# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Minecraft / Fabric 26.1.2 environment
minecraft_version=26.1.2
loader_version=0.19.2
fabric_api_version=0.150.0+26.1.2
loom_version=1.17.0-alpha.13
geckolib_version=5.5.1

# Mod metadata
mod_version=0.1.0-dev
maven_group=com.crpg
archives_base_name=ebb
mod_id=ebb
mod_name=Esoteric Ebb CRPG
