pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
        mavenCentral()
    }
}

rootProject.name = 'crpg-mod'
